apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phase2-hello
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hanq-moreh/argocd-gitops-lab.git
    targetRevision: main
    path: manifests/phase2-hello
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
